//
//*******
//
//	filename: UIColor+Crayola.h
//	author: Zack Brown
//	date: 21/05/2013
//*******
//

#import <UIKit/UIKit.h>

@interface UIColor (Crayola)

+ (UIColor *)almond;
+ (UIColor *)antiqueBrass;
+ (UIColor *)apricot;
+ (UIColor *)aquamarine;
+ (UIColor *)asparagus;
+ (UIColor *)atomicTangerine;
+ (UIColor *)bananaMania;
+ (UIColor *)beaver;
+ (UIColor *)bittersweet;
+ (UIColor *)black;
+ (UIColor *)blizzardBlue;
+ (UIColor *)blue;
+ (UIColor *)blueBell;
+ (UIColor *)blueGray;
+ (UIColor *)blueGreen;
+ (UIColor *)blueViolet;
+ (UIColor *)blush;
+ (UIColor *)brickRed;
+ (UIColor *)brown;
+ (UIColor *)burntOrange;
+ (UIColor *)burntSienna;
+ (UIColor *)cadetBlue;
+ (UIColor *)canary;
+ (UIColor *)caribbeanGreen;
+ (UIColor *)carnationPink;
+ (UIColor *)cerise;
+ (UIColor *)cerulean;
+ (UIColor *)chestnut;
+ (UIColor *)copper;
+ (UIColor *)cornflower;
+ (UIColor *)cottonCandy;
+ (UIColor *)dandelion;
+ (UIColor *)denim;
+ (UIColor *)desertSand;
+ (UIColor *)eggplant;
+ (UIColor *)electricLime;
+ (UIColor *)fern;
+ (UIColor *)forestGreen;
+ (UIColor *)fuchsia;
+ (UIColor *)fuzzyWuzzy;
+ (UIColor *)gold;
+ (UIColor *)goldenrod;
+ (UIColor *)grannySmithApple;
+ (UIColor *)gray;
+ (UIColor *)green;
+ (UIColor *)greenBlue;
+ (UIColor *)greenYellow;
+ (UIColor *)hotMagenta;
+ (UIColor *)inchworm;
+ (UIColor *)indigo;
+ (UIColor *)jazzberryJam;
+ (UIColor *)jungleGreen;
+ (UIColor *)laserLemon;
+ (UIColor *)lavender;
+ (UIColor *)lemonYellow;
+ (UIColor *)macaroniCheese;
+ (UIColor *)magenta;
+ (UIColor *)magicMint;
+ (UIColor *)mahogany;
+ (UIColor *)maize;
+ (UIColor *)manatee;
+ (UIColor *)mangoTango;
+ (UIColor *)maroon;
+ (UIColor *)mauvelous;
+ (UIColor *)melon;
+ (UIColor *)midnightBlue;
+ (UIColor *)mountainMeadow;
+ (UIColor *)mulberry;
+ (UIColor *)navyBlue;
+ (UIColor *)neonCarrot;
+ (UIColor *)oliveGreen;
+ (UIColor *)orange;
+ (UIColor *)orangeRed;
+ (UIColor *)orangeYellow;
+ (UIColor *)orchid;
+ (UIColor *)outerSpace;
+ (UIColor *)outrageousOrange;
+ (UIColor *)pacificBlue;
+ (UIColor *)peach;
+ (UIColor *)periwinkle;
+ (UIColor *)piggyPink;
+ (UIColor *)pineGreen;
+ (UIColor *)pinkFlamingo;
+ (UIColor *)pinkSherbert;
+ (UIColor *)plum;
+ (UIColor *)purpleHeart;
+ (UIColor *)purpleMountainsMajesty;
+ (UIColor *)purplePizzazz;
+ (UIColor *)radicalRed;
+ (UIColor *)rawSienna;
+ (UIColor *)rawUmber;
+ (UIColor *)razzleDazzleRose;
+ (UIColor *)razzmatazz;
+ (UIColor *)red;
+ (UIColor *)redOrange;
+ (UIColor *)redViolet;
+ (UIColor *)robinsEggBlue;
+ (UIColor *)royalPurple;
+ (UIColor *)salmon;
+ (UIColor *)scarlet;
+ (UIColor *)screaminGreen;
+ (UIColor *)seaGreen;
+ (UIColor *)sepia;
+ (UIColor *)shadow;
+ (UIColor *)shamrock;
+ (UIColor *)shockingPink;
+ (UIColor *)silver;
+ (UIColor *)skyBlue;
+ (UIColor *)springGreen;
+ (UIColor *)sunglow;
+ (UIColor *)sunsetOrange;
+ (UIColor *)tan;
+ (UIColor *)tealBlue;
+ (UIColor *)thistle;
+ (UIColor *)tickleMePink;
+ (UIColor *)timberwolf;
+ (UIColor *)tropicalRainForest;
+ (UIColor *)tumbleweed;
+ (UIColor *)turquoiseBlue;
+ (UIColor *)unmellowYellow;
+ (UIColor *)violetPurple;
+ (UIColor *)violetBlue;
+ (UIColor *)violetRed;
+ (UIColor *)vividTangerine;
+ (UIColor *)vividViolet;
+ (UIColor *)white;
+ (UIColor *)wildBlueYonder;
+ (UIColor *)wildStrawberry;
+ (UIColor *)wildWatermelon;
+ (UIColor *)wisteria;
+ (UIColor *)yellow;
+ (UIColor *)yellowGreen;
+ (UIColor *)yellowOrange;

@end
